name: Publish Package to npm

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '10.x'
      - run: npm ci
      - run: npx lockfile-lint --path package-lock.json --allowed-schemes "https:" "git+https:" --allowed-hosts npm github.com
      - run: ./create_config.sh
        env:
          SPHERE_CLIENT_ID: ${{ secrets.SPHERE_CLIENT_ID }}
          SPHERE_CLIENT_SECRET: ${{ secrets.SPHERE_CLIENT_SECRET }}
          SPHERE_PROJECT_KEY: ${{ secrets.SPHERE_PROJECT_KEY }}
      - run: npm test
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
